apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["1565"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["enp3s0f0"]
                }
            }
        ]
    }
